### PR TITLE
make cosmetic changes in Build.scala

### PR DESCRIPTION
**Pull request by adamkozuch**
I noticed that there is no ScalaTest in dependencies. Probably it will be used in future tests so I add it. Also I made small cosmetic changes in Build file. Is it OK?

### CODE REVIEW

**Comment by ianoc** [comment]
Cosmetic changes look good, not sure why you added the scalatest, is it being used now? or you think it just will be in future?

**Comment by adamkozuch** [comment]
I just noticed that there is a val with version of ScalaTest but there is no dependency. I figure it out that it will be used in future. Should I remove it for now?

**Comment by ianoc** [comment]
Yes i think that would be best, remove both for now

**Comment by adamkozuch** [comment]
Done.

**Comment by ianoc** [comment]
looks like a legit test failure:

```
[error] /home/travis/build/twitter/summingbird/project/Build.scala:46: commonsLangVersion is already defined as value commonsLangVersion
[error]   val commonsLangVersion ="2.6";
[error]       ^
[error] one error found
[error] (compile:compile) Compilation failed

```

**Comment by adamkozuch** [comment]
Sorry for that. Now it should be OK

**Comment by johnynek** [comment]
Can you merge with develop? The tests should be green now. Sorry for the issues.

**Comment by johnynek** [comment]
Thank you for your help!

**Pull request merged**
