### PR TITLE
remove as call in BatchedOperations

### PR DESCRIPTION
**Pull request by adamkozuch**

### CODE REVIEW

**Comment by adamkozuch** [comment]
Issue #574.

**Comment by adamkozuch** [comment]
Should I refactor from DataRange for instance this or just leave it? https://github.com/twitter/summingbird/blob/f04e6c90849c3fa177cfdec3a7174c5aa02251f4/summingbird-scalding/src/main/scala/com/twitter/summingbird/scalding/ScaldingPlatform.scala#L106-L107

**Comment by johnynek** [comment]
Let's leave the intersect method. DateRange does not have it, but we need it here.

**Comment by johnynek** [comment]
Also, sorry the tests are broken now. Let's let #594 get merged, then merge develop here and see that the tests are green, then we'll merge.

**Comment by johnynek** [comment]
Can you merge with develop and see if this goes green?

**Comment by johnynek** [comment]
Thank you!

**Pull request merged**
