### PR TITLE
call cascading backend to plan writes

### PR DESCRIPTION
**Pull request by fwbrasil**
@ttim This is required for summingbird to work with the new scalding version

### CODE REVIEW

**Comment by fwbrasil** [comment]
the CI won't pass since the branch has a dependency to an older scaling version. I can't change the version to use a new release because we're releasing scalding based on a branch. I tested this patch using the sandbox and it's ok internally cc/ @pankajroark

**Comment by johnynek** [comment]
we could publish a `0.18.0-RC1` so we could keep the CI here green.

**Comment by pankajroark** [comment]
@johnynek This branch is just for internal testing right now and we are ok with ci failing for this branch. Let me merge this for now.

**Comment by pankajroark** [comment]
This is just a personal branch, we can revert easily if there is a reason.

**Pull request merged**
