### PR TITLE
Support Scalding's 0.18.x branch

### PR DESCRIPTION
**Pull request by ttim**
This is reiteration over https://github.com/twitter/summingbird/pull/762 with correct fix.

I've released newest scalding internally and get green `./sbt clean test` of summingbird against this version. Note: to get it I reverted "Fix incompatibilities between storm and heron api" commit.

### CODE REVIEW

**Comment by ttim** [comment]
This PR is against `twitter_release` branch and will be later (as soon as we release scalding `0.18.x`) ported to develop

**Comment by dieu** [comment]
Can you look on CI?

**Comment by ttim** [comment]
@dieu just like previous PR this PR isn't going to pass through CI since scalding wasn't released. I tested it locally and tests are green.

**Comment by johnynek** [comment]
should we release a public RC to test these kinds of things?

**Comment by ttim** [comment]
@johnynek That totally makes sense, I'll try to release scalding RC today.

**Comment by johnynek** [comment]
we should publish an RC since I don't *think* anything is going to change that will break summingbird until the final is released.

PS: this is what we are running at Stripe:
https://github.com/stripe/summingbird/tree/v0.10.0-M8-stripe-scalding-18

which works with scalding 0.18

**Comment by dieu** [comment]
nit: can you bump dagon version to 0.3.1 to sync with scalding?

**Comment by johnynek** [comment]
Change looks good but it looks like failed. On a phone and can’t look now.

**Comment by ttim** [comment]
@johnynek my bad, this PR was against twitter release branch which doesn't compile because of some classes removed to make it compilable against heron.

Changed the base, should be good now.

**Comment by ttim** [comment]
Repos were broken as well (`http` instead of `https`, twitters maven repo doesn't serve over http anymore)

**Review by johnynek — APPROVED** [review]

**Review by dieu — APPROVED** [review]

**Pull request merged**
