### PR TITLE
remove Warnings and unused imports

### PR DESCRIPTION
**Pull request by AnishShah**
Hi,
I'm trying to remove Warnings that occur during Travis CI . And, also I removed unused imports in those files.
Please tell me if any changes are required.

Thanks.

### CODE REVIEW

**Comment by AnishShah** [comment]
Travis build is not starting. Any idea ?

**Comment by ianoc** [comment]
Travis is pretty terribly slow for us often, it might take up to an hour for it to kick in. Thanks for the PR btw, will take a look through today

**Comment by johnynek** [comment]
looks like the storm tests had their usual noisy failure. Restarted.

Looks good to me.

**Comment by johnynek** [comment]
Can you merge with develop? I think we have the tests fixed so they are not spuriously failing.

**Comment by AnishShah** [comment]
Cool

**Pull request closed without merging**
