### PR TITLE
Adding explicit hadoop deps; dfs-datastores to 1.3.6

### PR DESCRIPTION
**Pull request by egonina**

### CODE REVIEW

**Comment by ianoc** [comment]
LGTM

**Comment by johnynek** [comment]
@egonina is this still needed? If so, can we merge with develop and see if we can get it green?

**Comment by egonina** [comment]
Yes, I will do that. I think this will still be useful in giving better error messages in the Scalding layer.

**Comment by egonina** [comment]
All tests except for storm tests passed. Retrying storm tests

**Pull request merged**
