### PR TITLE
Add ComposedFunction for flatMapKeys/Values

### PR DESCRIPTION
**Pull request by johnynek**
If we use the rule that converts flatMapKeys/flatMapValues to a normal flatMap, we were hiding the inner functions so their names would be lost.

This does not effect using the DagOptimizer to remove the names, since we did not apply any other rules in that code.

### CODE REVIEW

**Comment by johnynek** [comment]
@pankajroark Can we merge this? I never got a review on it.

**Comment by pankajroark** [comment]
Are there any tests for the two new rules added here? If not, should we add them?

The change looks good otherwise.

**Comment by johnynek** [comment]
@pankajroark I have added some tests to exercise this. Thanks for keeping the testing bar high!

**Comment by pankajroark** [comment]
LGTM feel free to merge.

**Pull request merged**
