### PR TITLE
Fix the bug with reducer estimators not working

### PR DESCRIPTION
**Pull request by oscar-stripe**
Addresses #713 by using the same code path scalding uses.

### CODE REVIEW

**Comment by johnynek** [comment]
the tests are getting intolerable. We really need to look into the flakiness. I think they fail more than 1/2 the time on travis.

**Comment by johnynek** [comment]
@pankajroark this should be ready to merge when you can review.

**Comment by johnynek** [comment]
Maybe @benpence would also be good to look at this.

**Comment by ulyssepence** [comment]
+1 @johnynek nice work! I have a branch from several months ago to do something similar, but got distracted writing the test. This should also give us the flow(step) listeners for free right (I think you spoke about this yesterday)?

**Comment by johnynek** [comment]
Yes. This fixes that as well.

**Comment by johnynek** [comment]
So we could remove the mutate stuff and implement that with Config flow
listeners.

**Comment by pankajroark** [comment]
👍

**Pull request merged**
